from flask import Flask
from flask_cors import CORS

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '0f5945a3ad64f820eae65124' # generated by os.urandom
    CORS(app)
    from routes import main
    app.register_blueprint(main)
    return app


if __name__ == "__main__":
    app = create_app()
    app.run(debug=True, port=5000)
